name: test
on:
  push

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    name: Build tap image test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tap Build and Push
      id: tap-build-push
      uses: ./
      with:
        repository: simpleviewinc/tap-events-force
        cli_git_branch: ZEN-543-tap-workflow
        tap_ref: /ref/heads/tap-alias
        token: ${{ secrets.GIT_TOKEN }}
